plugins {
    id 'com.android.application'
}

android {
    namespace 'app.vercel.arrow_maze_psi.twa'
    compileSdk 35

    defaultConfig {
        applicationId 'app.vercel.arrow_maze_psi.twa'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
